### ISSUE TITLE
make test error

### ISSUE THREAD

**Issue by tallnuttcsiro** [benedictpaten/sonLib#28]
Get this error with make test. Also python can't find the modules.
.../bin/sh: 1: sonLib_kvDatabaseTest: not found
E/bin/sh: 1: sonLibTests: not found
E
======================================================================
ERROR: testFastaReadWriteC (bioioTest.TestCase)
Tests consistency with C version of this function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/OSM/HOME-MEL/all29c/bin/sonLib/bioioTest.py", line 185, in testFastaReadWriteC
    system(command)
  File "/OSM/HOME-MEL/all29c/bin/sonLib/bioio.py", line 185, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
RuntimeError: Command: sonLib_fastaCTest /tmp/tmp8537yf /tmp/tmpG6V7Df exited with non-zero status 127

======================================================================
ERROR: testCigarReadWrite (cigarsTest.TestCase)
Tests the C code for reading and writing cigars against the python parser for cigars.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/OSM/HOME-MEL/all29c/bin/sonLib/cigarsTest.py", line 57, in testCigarReadWrite
    system(command)
  File "/OSM/HOME-MEL/all29c/bin/sonLib/bioio.py", line 185, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
RuntimeError: Command: sonLib_cigarTest /tmp/tmpBZs1ok True exited with non-zero status 127

======================================================================
ERROR: testSonLibKVTokyoCabinet (kvdbTest.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/OSM/HOME-MEL/all29c/bin/sonLib/kvdbTest.py", line 18, in testSonLibKVTokyoCabinet
    system("sonLib_kvDatabaseTest --type=tokyocabinet")
  File "/OSM/HOME-MEL/all29c/bin/sonLib/bioio.py", line 185, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
RuntimeError: Command: sonLib_kvDatabaseTest --type=tokyocabinet exited with non-zero status 127

======================================================================
ERROR: testSonLibCTests (__main__.TestCase)
Run m,ost the sonLib CuTests, fail if any of them fail.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "allTests.py", line 30, in testSonLibCTests
    system("sonLibTests %s" % getLogLevelString())
  File "/OSM/HOME-MEL/all29c/bin/sonLib/bioio.py", line 185, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
RuntimeError: Command: sonLibTests CRITICAL exited with non-zero status 127

----------------------------------------------------------------------
Ran 19 tests in 20.710s

FAILED (errors=4)
make: *** [test] Error 4

**Comment by ambarrio** [comment]
Got exactly the same error than @tallnuttcsiro 

The sonLib_kvDatabaseTest program is there. The C function fails.

Any ideas?

**Comment by rfitak** [comment]
I also received the same errors as above.  In the Makefile, I changed:

PYTHONPATH=.. PATH=../../bin:$$PATH python allTests.py --testLength=SHORT --logLevel=CRITICAL
to
PYTHONPATH=.. PATH=./bin:$$PATH python allTests.py --testLength=SHORT --logLevel=CRITICAL

This fixed the problem above with not finding certain executables.  I am not sure why that particular path to "bin" was chosen.  However, I have now run into another problem with the tests when running "make test".  Here is the end of the output produced now from "make test":

OK (158 tests)

.
======================================================================
ERROR: testSonLibKVTokyoCabinet (kvdbTest.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/hpchome/biodept/frr6/LASTZ/MAFTOOLS/sonLib/kvdbTest.py", line 18, in testSonLibKVTokyoCabinet
    system("sonLib_kvDatabaseTest --type=tokyocabinet")
  File "/hpchome/biodept/frr6/LASTZ/MAFTOOLS/sonLib/bioio.py", line 185, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
RuntimeError: Command: sonLib_kvDatabaseTest --type=tokyocabinet exited with non-zero status 128

----------------------------------------------------------------------
Ran 19 tests in 78.278s

FAILED (errors=1)
make: *** [test] Error 1

At least now I am only down to 1 error.  Any ideas?

**Comment by awohns** [comment]
I'm having a similar issue. Did anyone ever resolve this error?

**Comment by Summer1019** [comment]
similar issue. Did this problem be solved?

**Comment by bioinformaticspcj** [comment]
I am also meeting the same problem. Did this problem be solved ?

**Comment by yuzhenpeng** [comment]
I am also meeting the same problem. Did this problem be solved ?

**Comment by diekhans** [comment]
what happens if you run 
`sonLib_kvDatabaseTest --type=tokyocabinet `

by hand

**Comment by yuzhenpeng** [comment]
I get it as follow.
`
$sonLib_kvDatabaseTest --type=tokyocabinet
running Tokyo Cabinet sonLibKVDatabase tests
Running test case readWriteAndRemoveRecords
Exception: ST_KV_DATABASE_EXCEPTION: requested Tokyo Cabinet database, however s                                       onlib is not compiled with Tokyo Cabinet support
Uncaught exception
`

**Comment by diekhans** [comment]
sonlib needs to be recompiled making sure it picks up tokyo cabinet and  Kyoto Tycoon .

see sonLib/include.mk for how it checks for the library and header locations

**Comment by lecook** [comment]
Hi there,
I also get this error with the command "make test". Is there anyway to solve this? Thanks

ok
testSonLibKTTests (__main__.TestCase)
Run the sonLib KyotoTycoon interface tests. ... skipped 'ktserver command is missing'
testSonLibKVTokyoCabinet (__main__.TestCase)
Run the sonLib TokyoCabinet interface tests. ... running Tokyo Cabinet sonLibKVDatabase tests
Running test case readWriteAndRemoveRecords
Exception: ST_KV_DATABASE_EXCEPTION: requested Tokyo Cabinet database, however sonlib is not compiled with Tokyo Cabinet support
Uncaught exception
ERROR
testSonLibRedisTests (__main__.TestCase)
Run the sonLib Redis interface tests. ... skipped 'hiredis pkg-config package is missing'

======================================================================
ERROR: testSonLibKVTokyoCabinet (__main__.TestCase)
Run the sonLib TokyoCabinet interface tests.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "allTests.py", line 75, in testSonLibKVTokyoCabinet
    system("sonLib_kvDatabaseTest --type=tokyocabinet")
  File "/data/gpfs/projects/punim0586/lecook/chipseq-pipeline/cross_species/bin/sonLib/src/sonLib/bioio.py", line 194, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
RuntimeError: Command: sonLib_kvDatabaseTest --type=tokyocabinet exited with non-zero status 128

----------------------------------------------------------------------
Ran 19 tests in 73.614s

FAILED (errors=1, skipped=2)
make: *** [test] Error 1
