### ISSUE TITLE
Syntax error in bioio.py, line 431?

### ISSUE THREAD

**Issue by ybukhman** [benedictpaten/sonLib#44]
Hi,

I get this error when running `make test` on hal. I also get the same error when I try to run `hal2assemblyHub.py`.

Example:

> bash-4.2$ hal2assemblyHub.py myhal.hal myhub_hub --lod \
> \> --alignability --gcContent --cladeExclusiveRegions --maxThreads 96\
> \> |& tee hal2assemblyHub.out
> Traceback (most recent call last):
>   File "/w5home/ybukhman/hal-20200815/hal/bin/hal2assemblyHub.py", line 24, in <module>
>     from sonLib.bioio import system, getTempFile
>   File "/w5home/ybukhman/hal-20200815/sonLib/bioio.py", line 431
>     os.chmod(dirName, 0777)
>                          ^
> SyntaxError: invalid token
>

**Comment by ybukhman** [comment]
Using the precompiled version of hal tools that comes with cactus works for me.
