### ISSUE TITLE
'make all' warning & 'make test' error: invalid syntax

### ISSUE THREAD

**Issue by sjfleck** [benedictpaten/sonLib#45]
Hi all,
I'm having an issue with 'make all' and make test. I'm using a lua system to load modules.

**Commands:**
git clone https://github.com/benedictpaten/sonLib.git
cd sonLib
module use -a /projects/academic/vaalbert/modulefiles/Allluas
module load anaconda3
module load sonLib
make all
make test

**Selected output from 'make all':**
_gcc -std=c99  -O3 -g -Wall --pedantic -funroll-loops -DNDEBUG       -I../externalTools/quicktree_1.1/include/  -I inc -I ../lib/  -c impl/*.c
impl/sonLibList.c: In function ‘st_list_sortP’:
impl/sonLibList.c:258:13: warning: ISO C forbids conversion of object pointer to function pointer type [-Wpedantic]
     return ((int (*)(const void *, const void *))fn)(*((char **)a), *((char **)b));
             ^
impl/sonLibList.c: In function ‘stList_sort’:
impl/sonLibList.c:262:76: warning: ISO C forbids conversion of function pointer to object pointer type [-Wpedantic]
     sort_r(list->list, stList_length(list), sizeof(void *), st_list_sortP, (void *)cmpFn);
                                                                            ^
impl/sonLibList.c: In function ‘st_list_sort2P’:
impl/sonLibList.c:267:56: warning: ISO C forbids conversion of object pointer to function pointer type [-Wpedantic]
     int (*cmpFn)(const void *, const void *, void *) = (int (*)(const void *, const void *, void *))(((void **)extra)[0]);
                                                        ^
impl/sonLibList.c: In function ‘stList_sort2’:
impl/sonLibList.c:273:24: warning: ISO C forbids conversion of function pointer to object pointer type [-Wpedantic]
     void *extra[2] = { (void *)cmpFn, (void *)extraArg };_

**Selected output from 'make test':**
_PYTHONPATH=.. PATH=../../bin:$PATH python allTests.py --testLength=SHORT --logLevel=CRITICAL
Traceback (most recent call last):
  File "allTests.py", line 8, in <module>
    import bioioTest
  File "/projects/academic/vaalbert/modulefiles/sonLib/bioioTest.py", line 69
    print "Got %s levels, %s fileNo and %s maxTempFiles" % (levels, fileNo, maxTempFiles)
          ^
SyntaxError: invalid syntax
make: *** [test] Error 1_

Any help with this issue would be greatly appreciated. Thank you!
-Steve

**Comment by xzk-fd** [comment]
Did you settle the problem, I meet the same problem , could you give me some help?

**Comment by glennhickey** [comment]
Please see: https://github.com/benedictpaten/sonLib/issues/47#issuecomment-1040357357
