### ISSUE TITLE
error in "make test"

### ISSUE THREAD

**Issue by thirtyeggs** [benedictpaten/sonLib#7]
Hi Benedict,

When I first ran "make test" I got many error massages like that:

```
.Running the command: sonLib_cigarTest /tmp/tmpKviSbo False
/bin/sh: sonLib_cigarTest: command not found
E......Running the command: sonLib_kvDatabaseTest --type=kyototycoon --host=localhost --port=1978
/bin/sh: sonLib_kvDatabaseTest: command not found
E.Running the command: sonLib_kvDatabaseTest --type=tokyocabinet
/bin/sh: sonLib_kvDatabaseTest: command not found
ERunning the command: sonLibTests DEBUG
/bin/sh: sonLibTests: command not found
E
======================================================================
ERROR: Tests consistency with C version of this function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gpfs2/projects/gec/tool/assemblathon1/sonLib/bioioTest.py", line 165, in testFastaReadWriteC
    system(command)
  File "/gpfs2/projects/gec/tool/assemblathon1/sonLib/bioio.py", line 160, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, i))
RuntimeError: Command: sonLib_fastaCTest /tmp/tmp0t00zf /tmp/tmpbVNOKW exited with non-zero status 32512
```

After adding sonLib/bin to $PATH manually, only following one error were remained:

```

======================================================================
ERROR: testSonLibKVKyotoTycoon (kvdbTest.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gpfs2/projects/gec/tool/assemblathon1/sonLib/kvdbTest.py", line 22, in testSonLibKVKyotoTycoon
    system("sonLib_kvDatabaseTest --type=kyototycoon --host=localhost --port=1978")
  File "/gpfs2/projects/gec/tool/assemblathon1/sonLib/bioio.py", line 160, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, i))
RuntimeError: Command: sonLib_kvDatabaseTest --type=kyototycoon --host=localhost --port=1978 exited with non-zero status 32768

----------------------------------------------------------------------
Ran 18 tests in 22.743s


```

Can I ask how I can remove it?
Thank you.

Yun

**Comment by Summer1019** [comment]
did this question be solved ?
